/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Account {
  'balance' : number,
  'accountType' : { 'checking' : null } |
    { 'savings' : null },
  'accountNumber' : string,
}
export interface Budget { 'category' : string, 'amount' : number }
export interface ChatMessage {
  'sender' : { 'ai' : null } |
    { 'user' : null },
  'message' : string,
  'timestamp' : Time,
}
export interface FinancialSummary {
  'totalBalance' : number,
  'monthlyExpenses' : number,
  'savingsRate' : number,
  'monthlyIncome' : number,
}
export interface HealthEvent {
  'status' : string,
  'detail' : string,
  'pillar' : string,
  'timestamp' : Time,
}
export interface LibraryResource {
  'id' : string,
  'title' : string,
  'featured' : boolean,
  'body' : string,
  'tags' : Array<string>,
  'description' : string,
  'timestamp' : Time,
  'readMinutes' : bigint,
  'category' : string,
}
export interface SensorEvent {
  'value' : string,
  'timestamp' : Time,
  'eventType' : string,
}
export type Time = bigint;
export interface Transaction {
  'transactionType' : { 'credit' : null } |
    { 'debit' : null },
  'description' : string,
  'timestamp' : Time,
  'category' : string,
  'amount' : number,
}
export interface UserProfile { 'name' : string, 'email' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addChatMessage' : ActorMethod<
    [string, { 'ai' : null } | { 'user' : null }],
    undefined
  >,
  'addLibraryResource' : ActorMethod<
    [string, string, string, string, Array<string>, bigint, boolean],
    undefined
  >,
  'addTransaction' : ActorMethod<
    [number, string, string, { 'credit' : null } | { 'debit' : null }],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createAccount' : ActorMethod<
    [string, { 'checking' : null } | { 'savings' : null }],
    undefined
  >,
  'getAccount' : ActorMethod<[], Account>,
  'getBudget' : ActorMethod<[string], Budget>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getChatHistory' : ActorMethod<[], Array<ChatMessage>>,
  'getFinancialSummary' : ActorMethod<[], FinancialSummary>,
  'getHealthLog' : ActorMethod<[], Array<HealthEvent>>,
  'getLibraryResource' : ActorMethod<[string], LibraryResource>,
  'getLibraryResources' : ActorMethod<[], Array<LibraryResource>>,
  'getSensorEvents' : ActorMethod<[], Array<SensorEvent>>,
  'getSpendingByCategory' : ActorMethod<[], Array<[string, number]>>,
  'getTransactions' : ActorMethod<[], Array<Transaction>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'logHealthEvent' : ActorMethod<[string, string, string], undefined>,
  'logSensorEvent' : ActorMethod<[string, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setBudget' : ActorMethod<[string, number], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];