/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Account = IDL.Record({
  'balance' : IDL.Float64,
  'accountType' : IDL.Variant({ 'checking' : IDL.Null, 'savings' : IDL.Null }),
  'accountNumber' : IDL.Text,
});
export const Budget = IDL.Record({
  'category' : IDL.Text,
  'amount' : IDL.Float64,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
});
export const Time = IDL.Int;
export const ChatMessage = IDL.Record({
  'sender' : IDL.Variant({ 'ai' : IDL.Null, 'user' : IDL.Null }),
  'message' : IDL.Text,
  'timestamp' : Time,
});
export const FinancialSummary = IDL.Record({
  'totalBalance' : IDL.Float64,
  'monthlyExpenses' : IDL.Float64,
  'savingsRate' : IDL.Float64,
  'monthlyIncome' : IDL.Float64,
});
export const HealthEvent = IDL.Record({
  'status' : IDL.Text,
  'detail' : IDL.Text,
  'pillar' : IDL.Text,
  'timestamp' : Time,
});
export const LibraryResource = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'featured' : IDL.Bool,
  'body' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'timestamp' : Time,
  'readMinutes' : IDL.Nat,
  'category' : IDL.Text,
});
export const SensorEvent = IDL.Record({
  'value' : IDL.Text,
  'timestamp' : Time,
  'eventType' : IDL.Text,
});
export const Transaction = IDL.Record({
  'transactionType' : IDL.Variant({ 'credit' : IDL.Null, 'debit' : IDL.Null }),
  'description' : IDL.Text,
  'timestamp' : Time,
  'category' : IDL.Text,
  'amount' : IDL.Float64,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addChatMessage' : IDL.Func(
      [IDL.Text, IDL.Variant({ 'ai' : IDL.Null, 'user' : IDL.Null })],
      [],
      [],
    ),
  'addLibraryResource' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Nat,
        IDL.Bool,
      ],
      [],
      [],
    ),
  'addTransaction' : IDL.Func(
      [
        IDL.Float64,
        IDL.Text,
        IDL.Text,
        IDL.Variant({ 'credit' : IDL.Null, 'debit' : IDL.Null }),
      ],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createAccount' : IDL.Func(
      [IDL.Text, IDL.Variant({ 'checking' : IDL.Null, 'savings' : IDL.Null })],
      [],
      [],
    ),
  'getAccount' : IDL.Func([], [Account], ['query']),
  'getBudget' : IDL.Func([IDL.Text], [Budget], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getChatHistory' : IDL.Func([], [IDL.Vec(ChatMessage)], ['query']),
  'getFinancialSummary' : IDL.Func([], [FinancialSummary], ['query']),
  'getHealthLog' : IDL.Func([], [IDL.Vec(HealthEvent)], ['query']),
  'getLibraryResource' : IDL.Func([IDL.Text], [LibraryResource], ['query']),
  'getLibraryResources' : IDL.Func([], [IDL.Vec(LibraryResource)], ['query']),
  'getSensorEvents' : IDL.Func([], [IDL.Vec(SensorEvent)], ['query']),
  'getSpendingByCategory' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64))],
      ['query'],
    ),
  'getTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'logHealthEvent' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'logSensorEvent' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setBudget' : IDL.Func([IDL.Text, IDL.Float64], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Account = IDL.Record({
    'balance' : IDL.Float64,
    'accountType' : IDL.Variant({
      'checking' : IDL.Null,
      'savings' : IDL.Null,
    }),
    'accountNumber' : IDL.Text,
  });
  const Budget = IDL.Record({ 'category' : IDL.Text, 'amount' : IDL.Float64 });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'email' : IDL.Text });
  const Time = IDL.Int;
  const ChatMessage = IDL.Record({
    'sender' : IDL.Variant({ 'ai' : IDL.Null, 'user' : IDL.Null }),
    'message' : IDL.Text,
    'timestamp' : Time,
  });
  const FinancialSummary = IDL.Record({
    'totalBalance' : IDL.Float64,
    'monthlyExpenses' : IDL.Float64,
    'savingsRate' : IDL.Float64,
    'monthlyIncome' : IDL.Float64,
  });
  const HealthEvent = IDL.Record({
    'status' : IDL.Text,
    'detail' : IDL.Text,
    'pillar' : IDL.Text,
    'timestamp' : Time,
  });
  const LibraryResource = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'featured' : IDL.Bool,
    'body' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'timestamp' : Time,
    'readMinutes' : IDL.Nat,
    'category' : IDL.Text,
  });
  const SensorEvent = IDL.Record({
    'value' : IDL.Text,
    'timestamp' : Time,
    'eventType' : IDL.Text,
  });
  const Transaction = IDL.Record({
    'transactionType' : IDL.Variant({
      'credit' : IDL.Null,
      'debit' : IDL.Null,
    }),
    'description' : IDL.Text,
    'timestamp' : Time,
    'category' : IDL.Text,
    'amount' : IDL.Float64,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addChatMessage' : IDL.Func(
        [IDL.Text, IDL.Variant({ 'ai' : IDL.Null, 'user' : IDL.Null })],
        [],
        [],
      ),
    'addLibraryResource' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Nat,
          IDL.Bool,
        ],
        [],
        [],
      ),
    'addTransaction' : IDL.Func(
        [
          IDL.Float64,
          IDL.Text,
          IDL.Text,
          IDL.Variant({ 'credit' : IDL.Null, 'debit' : IDL.Null }),
        ],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createAccount' : IDL.Func(
        [
          IDL.Text,
          IDL.Variant({ 'checking' : IDL.Null, 'savings' : IDL.Null }),
        ],
        [],
        [],
      ),
    'getAccount' : IDL.Func([], [Account], ['query']),
    'getBudget' : IDL.Func([IDL.Text], [Budget], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getChatHistory' : IDL.Func([], [IDL.Vec(ChatMessage)], ['query']),
    'getFinancialSummary' : IDL.Func([], [FinancialSummary], ['query']),
    'getHealthLog' : IDL.Func([], [IDL.Vec(HealthEvent)], ['query']),
    'getLibraryResource' : IDL.Func([IDL.Text], [LibraryResource], ['query']),
    'getLibraryResources' : IDL.Func([], [IDL.Vec(LibraryResource)], ['query']),
    'getSensorEvents' : IDL.Func([], [IDL.Vec(SensorEvent)], ['query']),
    'getSpendingByCategory' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64))],
        ['query'],
      ),
    'getTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'logHealthEvent' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'logSensorEvent' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setBudget' : IDL.Func([IDL.Text, IDL.Float64], [], []),
  });
};

export const init = ({ IDL }) => { return []; };